services:

  wordpress:
    container_name: ${DOMAIN}-wordpress
    image: wordpress:7.1.2
    ports:
      - ${PORT}:80
    environment:
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       # TODO divide variables into host and tld because of "ERROR: $table_prefix in wp-config.php can only contain numbers, letters, and underscores."
       WORDPRESS_TABLE_PREFIX: bnowakowski_
       VIRTUAL_HOST: ${DOMAIN}
    volumes:
      - ./config/apache/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf:ro
      - ./data/wordpress:/var/www/html
    restart: always
    cpus: '1.50'
    cpu_shares: 1024
    mem_limit: 1024m
    memswap_limit: 1024m
    pids_limit: 64
    external_links:
      - shared-mysql
    networks:
      - default
      - external_default

# docker network create external_default
networks:
    external_default:
      external: true
