services:

  wordpress:
    container_name: ${DOMAIN}-wordpress
    image: wordpress:6.9.1
    ports:
      - ${PORT}:80
    environment:
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       # TODO divide variables into host and tld because of "ERROR: $table_prefix in wp-config.php can only contain numbers, letters, and underscores."
       WORDPRESS_TABLE_PREFIX: bnowakowski_
       VIRTUAL_HOST: ${DOMAIN}
    volumes:
      - ./data/wordpress:/var/www/html
    restart: always
    external_links:
      - shared-mysql
    networks:
      - default
      - external_default
    #mem_limit: 600m
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 600M

# docker network create external_default
networks:
    external_default:
      external: true
