services:

  mysql:
    container_name: shared-mysql
    # https://community.home-assistant.io/t/mariadb-errors-after-update/424731
    # after upgrade run: make upgrade
    image: mariadb:13.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    cpus: '1.50'
    cpu_shares: 1024
    mem_limit: 1024m
    memswap_limit: 1024m
    pids_limit: 256
    networks:
      - default
      - external_default

# docker network create external_default
networks:
    external_default:
      external: true

#    network_mode: bridge

#    deploy:
#    resources:
#      limits:
#        memory: 400M
