version: '2.0'

services:

  wordpress:
    container_name: ${DOMAIN}-wordpress
    image: wordpress
    ports:
      - ${PORT}:80
    environment:
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/wordpress:/var/www/html
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: ${DOMAIN}-mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
#    mem_limit: 4000000000 # 1000000000 = 1G
    mem_limit: 400m
#    deploy:
#    resources:
#      limits:
#        memory: 400M
