version: '3.0'

services:

  wordpress:
    image: wordpress
    ports:
      - 8082:80
    env_file:
      - variables.env
    volumes:
      - ./data/wordpress:/var/www/html
    restart: always

  mysql:
    image: mariadb
    env_file:
      - variables.env
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always

