version: '3.0'

#    resources:
#      limits:
#        memory: 128M

services:

  wordpress:
    container_name: ${DOMAIN}-wordpress
    image: wordpress
    ports:
      - ${PORT}:80
    environment:
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/wordpress:/var/www/html
    restart: always
    depends_on:
      - mysql

  mysql:
    container_name: ${DOMAIN}-mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
#    mem_limit: 256m
#    deploy:
    resources:
      limits:
        memory: 128M
